### PR TITLE
Added fix for matching escaped slashes

### LINKED ISSUE #12: backslashes stripped out of strings
With the following config:

```
 "quotes": {
    "type": "single",
    "avoidEscape": true
  }
```

I start with this:

`'\\"ESRI Shapefile\\"'`

If I run `esformatter` it strips off one quote, which is incorrect, and I end up with:

`'\"ESRI Shapefile\"'`

Running `esformatter` a second time, I end up with:

``'"ESRI Shapefile"'``

Original issue, for context: https://github.com/maxogden/standard-format/issues/84#issuecomment-124235400

### PR DESCRIPTION
**Pull request by twolfson**
As brought up in #12, we have been stripping slashes from escaped slashes. This PR remedies that by greedily matching all escaped slash pairs. In this PR:

- Added regression tests for escaped slashes
- Added fix for escaped slashes
- Fixes #12 

/cc @millermedeiros @feross

### CODE REVIEW

**Comment by millermedeiros** [comment]
it's a little bit confusing but behavior looks correct to me

**Comment by twolfson** [comment]
Any advice on how to make it more clarifying?

File: index.js [hunk 1]
```diff
@@ -43,18 +43,29 @@ exports.tokenBefore = function(token) {
...
+    //   - We want to start on a non-slash character to only match at boundaries
+    //      (i.e. `^|\`, the 4 slashes are 1 slash in RegExp)
+    //   - We want to prevent replacing escaped slashes (i.e. `\\` should not be replaced, this is 8 slashes in RegExp)
+    //   - We want to replace `\"` with `"` as the slash is unnecessary
+    //      so consume `\` but don't match it and preserve the quote
+    ///  - We match as many pairs as possible for `\"` due to requiring a leading word boundary on our next match (which won't exist)
+    var alternateEscape = new RegExp('(^|[^\\\\])((\\\\{2})*)((\\\\' + alternate + ')+)', 'g');
+    content = content.replace(alternateEscape, function replaceQuotes (input, boundaryChar, leadingEscapedSlashes, leadingEscapedSlash, escapedQuoteChars, escapedQuoteChar, match) {
+      // DEV: We divide the escapedQuoteChars by 2 since there are 2 characters in each escaped part ('\\"'.length === 2)
+      return boundaryChar + leadingEscapedSlashes + new Array((escapedQuoteChars.length / 2) + 1).join(alternate);
```
Comment (millermedeiros) [inline index.js]: what about we extract the `new Array(len).join()` into a `repeat` function? that way it's a little bit clearer:

```js
function repeat(str, n) {
  return new Array(n + 1).join(str);
}
```

Comment (twolfson) [inline index.js]: :+1:

**Comment by twolfson** [comment]
I will take care of the better format by the end of the weekend.

File: index.js [hunk 2]
```diff
@@ -43,18 +43,29 @@ exports.tokenBefore = function(token) {
...
+    //   However, don't remove escapes from slashes (e.g. '\\"' -> '\\"')
+    // DEV: RegExp explained:
+    //   - We want to start on a non-slash character to only match at boundaries
+    //      (i.e. `^|\`, the 4 slashes are 1 slash in RegExp)
+    //   - We want to prevent replacing escaped slashes (i.e. `\\` should not be replaced, this is 8 slashes in RegExp)
+    //   - We want to replace `\"` with `"` as the slash is unnecessary
+    //      so consume `\` but don't match it and preserve the quote
+    ///  - We match as many pairs as possible for `\"` due to requiring a leading word boundary on our next match (which won't exist)
+    var alternateEscape = new RegExp('(^|[^\\\\])((\\\\{2})*)((\\\\' + alternate + ')+)', 'g');
+    content = content.replace(alternateEscape, function replaceQuotes (input, boundaryChar, leadingEscapedSlashes, leadingEscapedSlash, escapedQuoteChars, escapedQuoteChar, match) {
```
Comment (millermedeiros) [inline index.js]: since `leadingEscapedSlash` and `escapedQuoteChar` are not being used what do you think about using a non-capturing group?

```diff
diff --git a/index.js b/index.js
index 4892e6a..0c4fc33 100644
--- a/index.js
+++ b/index.js
@@ -52,21 +52,25 @@ exports.tokenBefore = function(token) {
     //   - We want to replace `\"` with `"` as the slash is unnecessary
     //      so consume `\` but don't match it and preserve the quote
     ///  - We match as many pairs as possible for `\"` due to requiring a leading word boundary on our next match (which won't exist)
-    var alternateEscape = new RegExp('(^|[^\\\\])((\\\\{2})*)((\\\\' + alternate + ')+)', 'g');
-    content = content.replace(alternateEscape, function replaceQuotes (input, boundaryChar, leadingEscapedSlashes, leadingEscapedSlash, escapedQuoteChars, escapedQuoteChar, match) {
+    var alternateEscape = new RegExp('(^|[^\\\\])((?:\\\\{2})*)((?:\\\\' + alternate + ')+)', 'g');
+    content = content.replace(alternateEscape, function replaceQuotes (input, boundaryChar, leadingEscapedSlashes, escapedQuoteChars, match) {
       // DEV: We divide the escapedQuoteChars by 2 since there are 2 characters in each escaped part ('\\"'.length === 2)
-      return boundaryChar + leadingEscapedSlashes + new Array((escapedQuoteChars.length / 2) + 1).join(alternate);
+      return boundaryChar + leadingEscapedSlashes + repeat(alternate, escapedQuoteChars.length / 2);
     });
 
     // If the first character is a quote, escape it (e.g. "'hello" -> '\'hello')
     //   or if a character is an unescaped quote, escape it (e.g. "hello'" -> 'hello\'')
     // If we are an unescaped set of quotes, escape them (e.g. "hello'" -> 'hello\'', "hello''" -> 'hello\'\'')
     // DEV: JavaScript starts the next match at the end of the current one, causing us to need a function or loop.
-    var quoteEscape = new RegExp('(^|[^\\\\])((\\\\{2})*)(' + quote + '+)', 'g');
-    content = content.replace(quoteEscape, function replaceQuotes (input, boundaryChar, leadingEscapedSlashes, leadingEscapedSlash, quoteChars, match) {
-      return boundaryChar + leadingEscapedSlashes + new Array(quoteChars.length + 1).join('\\' + quote);
+    var quoteEscape = new RegExp('(^|[^\\\\])((?:\\\\{2})*)(' + quote + '+)', 'g');
+    content = content.replace(quoteEscape, function replaceQuotes (input, boundaryChar, leadingEscapedSlashes, quoteChars, match) {
+      return boundaryChar + leadingEscapedSlashes + repeat('\\' + quote, quoteChars.length);
     });
     token.value = quote + content + quote;
   }
 };
 
+function repeat(str, n) {
+  return new Array(n + 1).join(str);
+}
+
```

Comment (twolfson) [inline index.js]: Yea, we can do that.

**Comment by twolfson** [comment]
I have taken care of the comments as requested.

**Comment by millermedeiros** [comment]
thanks a lot for all the fixes!
